### ISSUE TITLE
Develop Backend Prototype for Data Storage and Login Functionality

### ISSUE THREAD

**Issue by stuar7** [Ishi01/CITS5505Group41Project#3]
## Objective
Develop a backend prototype that can store data and provide login functionality to the frontend.

## Tasks
- [ ] Set up a new branch for backend prototype development
- [ ] Set up the flask environment.
- [ ] Set up the SQLite environment.
- [ ] Design and implement a prototype database scheme for user logins
- [ ] Create API endpoints for user registration and login
- [ ] Implement user login and logout
- [ ] Integrate the backend with the frontend to display successful login messages
