### ISSUE TITLE
Implement Frontend Prototype with SVG jQuery Map

### ISSUE THREAD

**Issue by cloud9ight** [Ishi01/CITS5505Group41Project#4]
## Objective
Create a frontend prototype that utilises the SVG jQuery map plugin.

## Tasks
- [x] Set up a new branch for frontend prototype development
- [x] Create a prototype user interface for the SVG map and user login
- [x] Integrate the SVG map
- [x] Integrate the jQuery plugin
- [x] Ensure basic jQuery overlay and mouseover events work
